version: '3'
services:
  api:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
  client:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - api
  mongo:
    image: mongo
    ports:
      - "27017:27017"